version: '2.4'

services:
  #########################################
  #          Poker Website royalflushsaga #
  #########################################
  web:
    image: dockerregistry.artindustrial-it.com/paulhager/pokerwebsite
    container_name: pokerwebsite_app
    hostname: pokerwebsite
    restart: unless-stopped
    volumes: [ ]
    networks:
      - proxy
  db:
    image: postgres:14.4
    hostname: db
    container_name: pokerwebsite_db
    environment:
      POSTGRES_DB: pokerWebsite
      POSTGRES_USER: pWUser
      POSTGRES_PASSWORD: yourdbpassword
    networks:
      - proxy
    volumes:
      - postgres_data:/var/lib/postgresql/data
networks:
  proxy:
    name: proxy
volumes:
  postgres_data:
    driver: local
